name: Delete Workflow Runs
on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1日0点执行
jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: colbyfayock/delete-workflow-runs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 30     # 删除30天前的记录
          retain_min_count: 6  # 至少保留6条记录
